FROM php:7.4-apache
RUN apt-get update && apt-get install -y libpq-dev && docker-php-ext-install pdo pgsql pdo_pgsql && service apache2 restart
COPY script.php /usr/src/myapp/script.php
WORKDIR /usr/src/myapp
CMD [ "php", "./script.php" ]